### ISSUE TITLE
Future Events JSON format - And all other JSON format 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#26]
please format the json as you did for all events  
# please check all JSON and make sure that they are structured properly

this is what is being returned 

{"Events":{"5":{"name":"ACM","owner":"1","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"Event for CS students","startDateTime":"2016-04-30 12:00:00","endDateTime":"2016-04-30 13:00:00","location":"GITC 2000","attendees":null},"6":{"name":"IEEE","owner":"2","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"Event for EE students","startDateTime":"2016-05-02 15:00:00","endDateTime":"2016-05-02 16:30:00","location":"GITC 3000","attendees":null}}}

**Comment by aml35** [comment]
done

**Comment by tramrattan** [comment]
JSON format still not correct 

this is what is being returned 

future events: {"id":"6","name":"IEEE","owner":"2","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"Event for EE students","startDateTime":"2016-05-02 15:00:00","endDateTime":"2016-05-02 16:30:00","location":"GITC 3000","attendees":null}

// no null objects - should be an empty array 

the format for this json should be 

{ "events": [  array of events ] }
